apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-url-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: short-url
  template:
    metadata:
      labels:
        app: short-url
    spec:
      containers:
        - name: short-url-container
          image: short-url-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
