apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-url-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: short-url
  template:
    metadata:
      labels:
        app: short-url
    spec:
      containers:
      - name: short-url-container
        image: rehanrajpoot/short-url-app:latest
        ports:
        - containerPort: 5000
