apiVersion: v1
kind: Service
metadata:
  name: short-url-service
spec:
  type: NodePort
  selector:
    app: short-url
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
